version: '3'

services:
  balanceapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortlinkapp
    depends_on:
      - "db_mysql"
    ports:
      - '9000:9000'
    command: ["/go/src/shortlinkapp/scripts/wait-for-it.sh", "db_mysql:3306", "--", "/go/src/shortlinkapp/bin/shortlinkapp"]

  db_mysql:
    image: mysql:8.0.21
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'
    #      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: shortlinkapp

#volumes:
#  dbdata:
#    driver: local